language: python

python:
  - 3.6
  # - 3.7
  # - pypy3

install:
  - pip install poetry
  - poetry install -v

script:
  - poetry run tox -v

after_success:
  - pip install python-coveralls
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
  - secure: DKqwvIgiK11z7oKnfO1GMnPo8sfTAvVzS+9YOgzQlStYgY2jh5nJpU+3JvDPRh/0Ii5Ee/0FqiwqKdfiD+8ljWWCUdfZwW5Bc8KsMm8ZIEDXoq3BRma2TajLz4K7A1urwQ0xd4g7h2xBlvJSGnV2lIUNAWWfvYsbDBnzjqUnIUgSjXTNwV+iuIsfXN0dl5Xc18NCki/Uvg5odEN0TBbadyAD/MYVD2cnNrSWeUKFu8ttneKUt3oRWlLqZEPO88o2j2TlvXrWjgwtpaI4uzHbP5KHbj8yJojBoPuzEIXkZo1m5Zf5Afsbb1nDSOZSvZxEf0fPv2Jcj75UjuBfDzEEJ++0lmNRpQNMspXPwEiY4N+j04KoHB7tFuBweGv5b/6J9dJzn/vpb/T1JEERdqGAvikl2Ok+sLYGdgUBWQfRr9XA6v8Cvx51J6ehRFjCm3gWooOiiVwmahJawxMdHmCxza3F7zpBeFK1o8+jlc4jXmZa7DWiOv9VTeRp50Y+9Ytx6H8sNiknQPr9xkH5IsQSwj0USNLFo38VPixLxnILgyXV7ggKUEsXdrEcRFssD1fOrzpuAU3l9VyqH9BDGzcifDT574EFLO/az6sDJz7iFlvk5m4ga6F6OaupNXsQmXrkoE0clvMMlbSq2wr3bDIBe1cY9oIGKrCkKv0R3jlfZDc=
  - secure: V7MUriHSqwFPHlf7lnedssnuqZR37Vx4Y3+LEmmLnDi6/ekcDlSNQrqo6ufI0kImsUiq8r34v0urWCeqB0cR3pp0FdK1wnB7Q/T9e/0d58DmA/6oWbsZThg8/IFmBkf+ryyIfnwQUmovw3lAiOuOUWJvyiGh1dA8+qe2vakY7NjOR0kaSOzBucDXP/divxNy0zyjpdBUi4UWy25aZAfgt237HF/hQg1Sf18NRCPQ+ohwm4pe8TGGQLrvaPnwo73DAnu2f1hckQWkB2cgfDQhP4mwnSP/jRrE4IIXjJW0KQLVRJYav0shAL5ocjtZ7pupmWhakUOG5+WKTKkKO14KS1CBh2S75VTyqWR3P5yi1TIDfQWYp8mO6hMZgm73PVGUQzqBcrbTvmOFRQr8eWjR4GXOiwmhVHYrJOBc6Y+yCsiW5wCI2Oal0Fe+L0iRk6NQhSKMkxju8E8r9ma5uP1bn/r60dW/wI8Kjuw5j3302nbkzhffQhHS88a23mgjUT5JBFywibq9lZzMAz1CR+UU4pkFc7CQWGqU3FSiFq5/lhKYIyrpbZYpfWzeYTixqS7teao+sco4bNoD082HZ+v9ffqOdR8sfZ9qUoFYZHVb8xpJlYlsKrYQPnFquK3UjDtG8SiEoW99uuKrRvhD5VeAiq/dAeE7o8z7gPaFIXodufc=
before_deploy:
  - poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -u $PYPI_USER -p $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
