language: python
python:
  # - '3.5' # old flake8 not respecting noqa
  - '3.6'
  - '3.6-dev'
  # - '3.7-dev'
  # - 'pypy3.6'
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install tox-travis
script:
  - flake8 tensionflow
  - tox
after_success:
  - coveralls
  - codecov
